# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
